Fix for Multi-day weekly recurring event missing first instance
kewisch/ical.js pull request #333
Opened 2017-07-29 02:28 UTC by arunpandianp

This fixes #300 

`ICAL.Time` by default has `Sunday` as the week start and `ICAL.Recur` treats `Monday` as the default start of week. 

The change is to get dayOfWeek relative to the `rrule.wkst` before comparing. As Sunday > Monday inside a week if wkst is Monday. 

While this fixes #300, there are still places where I see similar logic being used. I'll try to look in to them.

2017-08-02 07:21 UTC, arunpandianp commented
@mschroeder @kewisch can you take a look?

2017-08-04 18:45 UTC, mschroeder commented
@arunpandianp, I'll review your pull request over the weekend.

2017-08-06 21:09 UTC, mschroeder commented
@arunpandianp, I cannot finish the review today, so I will get back to you during the week, but I already started to look into your changes.

2017-08-06 23:05 UTC, arunpandianp commented
@mschroeder thanks :)

2017-08-13 11:55 UTC, mschroeder requested changes
Sorry for taking so long to review your pull request. I have some comments you should consider. Also, feel free to contact me or start a discussion.

2017-08-13 11:55 UTC, mschroeder commented on test/recur_iterator_test.js
> +      testRRULE('FREQ=WEEKLY;COUNT=3;BYDAY=MO,SU,TU', {
You should add comments above the testcases to describe the scenarios explicitly tested.

2017-08-13 11:55 UTC, mschroeder commented on lib/ical/recur.js
> +   * @param {ICAL.Time.weekDay=} aWeekStart
The documented argument name does not match the method signature. `aWeekStart` should be used everywhere to be consistent.

2017-08-13 11:55 UTC, mschroeder commented on lib/ical/recur.js
> +   * @param {ICAL.Time.weekDay=} aWeekStart
The documented argument name does not match the method signature. `aWeekStart` should be used everywhere to be consistent.

2017-08-13 11:55 UTC, mschroeder commented on lib/ical/time.js
> +    dayOfWeek: function icaltime_dayOfWeek(aFirstDayOfWeek) {
This function should get some more unit tests now with the optional argument.

2017-08-13 11:55 UTC, mschroeder commented on lib/ical/time.js
> +     * @param {ICAL.Time.weekDay=} aWeekStart
The documented argument name does not match the method signature. `aWeekStart` should be used to be consistent in the file.

2017-08-13 11:55 UTC, mschroeder commented on lib/ical/time.js
>        h = ((h + 6) % 7) + 1;
The normalization step with variable first day of week can be written in a single line as `h = ((h + 7 - firstDow) % 7) + 1;`.

2017-08-13 11:55 UTC, mschroeder commented on lib/ical/recur.js
> +    var dow = num;
This can be written in a single statement: `var dow = ((num - firstDow + 7) % 7) + 1;`

2017-08-13 11:55 UTC, mschroeder commented on lib/ical/recur.js
> +    var dow = DOW_MAP[string];
This can be written in a single statement: `return ((DOW_MAP[string] - firstDow + 7) % 7) + 1;`

2017-08-13 11:55 UTC, mschroeder commented on lib/ical/recur_iterator.js
> +    ruleDayOfWeek: function ruleDayOfWeek(dow, aFirstDayOfWeek) {
`aWeekStart` should be used everywhere to be consistent. Maybe you want to add documentation to this function.

2017-08-13 11:55 UTC, mschroeder commented on lib/ical/recur.js
> +  ICAL.Recur.numericDayToIcalDay = function toIcalDay(num, aFirstDayOfWeek) {
This function should get some more unit tests now with the optional argument.

2017-08-13 11:55 UTC, mschroeder commented on lib/ical/recur.js
> +  ICAL.Recur.icalDayToNumericDay = function toNumericDay(string, aFirstDayOfWeek) {
This function should get some more unit tests now with the optional argument.

2017-08-15 13:28 UTC, arunpandianp commented
@mschroeder addressed your comments.

2019-10-06 12:44 UTC, kewisch commented
I've manually rebased this on master and fixed it in 7b8d59d6cded33d08da617ca42696755fadd6587. Thanks for the patch!

2019-10-06 12:44 UTC, closed without merging