recur_expansion.js: EXDATE can be DATE and DTSTART can be DATE-TIME
kewisch/ical.js pull request #438
Opened 2020-04-19 20:43 UTC by dilyanpalauzov

When EXDATE is in DATE format and DTSTART is DATE-TIME, then to determine whether a ocurrence shall be excluded, the occurence shall be converted to DATE and then compared to EXDATE.

This applies also for the very first EXDATE, when it coincides with DTSTART.

2020-11-11 08:29 UTC, tasn commented
Thanks for the fix, but it doesn't seem to fix the issues in #458. Could you take a look? Maybe you missed something?
Thanks!

2020-11-11 09:14 UTC, dilyanpalauzov commented
No.  This is from April 2020 and the other is from November 2020.

2020-11-11 09:16 UTC, tasn commented
Yeah, I saw that, but they seem to be addressing the same underlying issue, so maybe the fix here is incomplete?
Thanks for your work btw!

2020-11-15 11:30 UTC, dilyanpalauzov commented
I patch locally ical.js to fix problems I have and submit the changes for inclusion upstream.  You can see under the current Pull Requests list, that I have done this more than once.  I have not experienced the problem you refer to.  The fixes I submit are not considered within reasonable time and essentially ignored (N.B. the last commit in thr master branch is from me: I say this for completeness).  If I work on a problem I do not have, and submit patch upstream, for me it it not foreseeable, whether my work will eventually have impatct on the common good, or will be just lost time.

2020-11-15 13:15 UTC, tasn commented
I think I didn't explain myself very well. I'm very appreciative of your fixes, and I realise you are scratching your own itches. I'm thankful for you making this library better, as I rely on it in my app!
I was just trying to point out that what this seems to fix doesn't fix the other issue which I thought was very similar and closely related. I wanted to point that out because: I obviously want it fix, but also because it may indicate your current fix is incomplete.

As for your PRs not being reviewed: yup, that's annoying. I feel you. :|

Thanks again for all your work!

2021-07-13 11:37 UTC, kewisch requested changes
Would be great if you could add some tests for this case. I skipped reviewing the parts that belong to your other PRs, let's see if we can get them merged first :)

2021-07-13 11:37 UTC, kewisch commented on lib/ical/recur_expansion.js
> +          if (compare > 0) {
Can you explain why we need to switch the sign here?

2021-07-13 11:37 UTC, kewisch commented on lib/ical/recur_expansion.js
> +    _compare_special: function(a, b) {
If you don't mind maybe we can do some bikeshedding here. "Special" seems fairly general, not easy to understand what the function does just based on name. I was thinking `compareTimeless` but then again it doesn't always compare without time. Do you have a suggestion on how we can make this more clear?

2021-07-13 11:58 UTC, dilyanpalauzov commented on lib/ical/recur_expansion.js
> +          if (compare > 0) {
I cannot explain this today.  When the case was opened last year, I was aware of the context.  Now I do not know and the only way to find out, is to dig in the code.  Anyway, two lines above the comparisson function is changed from compare=this.exDate.compare to compare=this._compare_special and using tests somehow, the sign change was found to be correct.

2021-07-17 18:03 UTC, dilyanpalauzov commented on lib/ical/recur_expansion.js
> +    _compare_special: function(a, b) {
I have no suggestion.  You can rename it as you want.

2021-12-05 14:44 UTC, closed without merging