event.isRecurring() does not repeat with RECURRENCE-ID without RANGE
kewisch/ical.js pull request #457
Opened 2020-10-28 13:50 UTC by dilyanpalauzov

Evolution creates instances of events, which contain RRULE and RECURRENCE-ID
without RANGE parameter.  Since the RANGE is not THISANDFUTURE, but absent,
such events do not recur.

https://gitlab.gnome.org/GNOME/evolution/-/issues/1180

Currenlty isRecurring() returns under these conditions TRUE, instead of FALSE.

2020-12-13 17:29 UTC, MartenBE commented
This bug also causes problems in the Nextcloud Calendar app. Is there any update if this can be merged?

2021-07-13 10:54 UTC, kewisch requested changes
I know it has been a while, but any chance you could add a test for this?

2021-07-13 10:54 UTC, kewisch commented on lib/ical/event.js
> +     * Checks if the event is recurring.  The event is not recurring if it has RECURRENCE-ID property without RANGE parameter.
```suggestion
     * Checks if the event is recurring. The event must have an RRULE or RDATE property, or a
     * RECURRENCE-ID with the respective RANGE parameter.
```

2021-07-13 11:14 UTC, dilyanpalauzov commented
I do not understand the test framework and learning it will cost significant amount of time, to add a simple test.  So, my answer is - no.

2021-10-26 08:17 UTC, dilyanpalauzov commented on lib/ical/event.js
> +     * Checks if the event is recurring.  The event is not recurring if it has RECURRENCE-ID property without RANGE parameter.
I have no objection to any wording of thr comments.  The last sentence should end with ' in order to be recurring’.

2022-11-29 09:15 UTC, dilyanpalauzov commented
Now updated to ES6.

2024-04-02 00:53 UTC, closed without merging