Fix Stringification for Parameters with Multiple Values
kewisch/ical.js pull request #460
Opened 2020-12-30 09:51 UTC by zlajo

I am currently trying to solve a problem when synchronizing contacts between nextcloud and macOS Contacts. One part of the problem seems to be that parameters with multiple values are not serialized correctly by ICAL.stringify. A phone number with multiple types (e.g. "HOME" and "VOICE") is serialized as _TEL;TYPE="HOME,VOICE:0815 1234"_, which seems to be wrong according to the specification ([https://tools.ietf.org/html/rfc2426#section-4](https://tools.ietf.org/html/rfc2426#section-4) -> _param = param-name "=" param-value *("," param-value)_). The correct serialization should be _TEL;TYPE=HOME,VOICE:0815 1234_ or _TEL;TYPE="HOME","VOICE":0815 1234_.

My changes slightly update the serialization process for exactly this type of parameters. I have also added some tests to illustrate my changes.

Another possibility to fix my problem at hand would be to update the parameter configuration for phone numbers in design.js but I think that my solution which addresses the underlying problem is more general and hopefully future-proof. 

Please let me know if my fix has any flaws or needs some further discussion!

2021-07-13 10:45 UTC, kewisch requested changes

2021-07-13 10:45 UTC, kewisch commented on lib/ical/stringify.js
>            value = stringify.multiValue(value, multiValue, "unknown", null, designSet);
We are iterating `value` with `map` up to three times here, I think it might make sense to reduce this to one iteration.

2021-11-15 19:15 UTC, dilyanpalauzov commented on lib/ical/stringify.js
> +    } else if (value.startsWith('"') &&
Atfer `return` there is no need for `else` (in any language).

2022-11-10 08:40 UTC, dilyanpalauzov commented
https://github.com/kewisch/ical.js/pull/555 is a different approach to the same problem.

2024-04-02 00:53 UTC, closed without merging