Fix Issue #515
kewisch/ical.js pull request #516
Opened 2022-06-22 08:41 UTC by kaie

Fall back to date only parsing

2022-06-22 08:46 UTC, kaie commented
@darktrojan could you please approve the workflows and have a look? Thanks

2022-06-22 09:09 UTC, darktrojan commented
I don't have those powers. @kewisch?

2022-06-30 14:11 UTC, kewisch commented on lib/ical/time.js
> +    if (useDateOnly) {
Let's gate the leniency on `!ICAL.design.strict`

2022-06-30 14:16 UTC, kewisch requested changes
A test would be marvelous. 

I'm not sure why the linters are failing, but at least on this branch we use var (almost) everywhere for backwards compat. I need to merge the ES6 branch before it diverts too much, here we can use all the modern things.

I suspect we passed the deadline you were looking to make? Apologies in advance. If not then I'd be fine skipping the test in order to push this out, as long as you can follow up with the test a bit later.

2022-07-13 14:11 UTC, kaie commented
abandoning per request from Lasana

2022-07-13 14:11 UTC, closed without merging