recur_expansion.js: fix iterator with RDATE-only recurrence
kewisch/ical.js pull request #534
Opened 2022-09-16 17:10 UTC by dilyanpalauzov

When iterating with
```javascript
  e is an event-component
  if (e.isRecurring() {
     let i = e.iterator();
     while (n = i.next()) {
       o = g.getOccurrenceDetails(obj)
       …
     }
  }
```
on the first iteration the DTSTART instance shall be returned.  It is returned, when there is RRULE.  In the lack of this change, on the first iteration, when RDATE is present without RRULE, the first RDATE instance is returned.

@darktrojan  how does Thunderbird handle VEVENTS with RDATE but without RRULE.  These are presented correct in the UI.  But the instances cannot be obtained by getting an iteratior of the event and then calling .next().  The reason is, that the very first iteration skips then the DTSTART-instance.  The DTSTART instance is not skipped by the iterator.next() when the VEVENT has RRULE.

2022-10-16 22:37 UTC, darktrojan commented
> @darktrojan how does Thunderbird handle VEVENTS with RDATE but without RRULE. These are presented correct in the UI. But the instances cannot be obtained by getting an iteratior of the event and then calling .next(). The reason is, that the very first iteration skips then the DTSTART-instance. The DTSTART instance is not skipped by the iterator.next() when the VEVENT has RRULE.

Thunderbird doesn't use this code for RDATEs, it maintains a list of them and does iteration itself. So I'm not familiar with how this bit works at all.

2022-11-09 23:15 UTC, darktrojan requested changes
In my very limited understanding of how this particular bit works, this looks okay to me. But it needs updating for ES6.

2024-04-13 21:37 UTC, kewisch commented
@dilyanpalauzov looks like you are actively working on this one, anything I can do to help get this merged?

2024-04-14 13:31 UTC, dilyanpalauzov commented
This change for proposal is one and a half years old.  I do not know what is missing to get it merged.  I see now it contains a test, which is failing.  Sorry, I do not know anymore what was going on.

2024-04-14 20:03 UTC, kewisch commented
Ah no problem, I had seen a recently referenced commit which made me assume. If you do feel like picking this up again I'm happy to give reviews some priority.

2025-06-28 19:16 UTC, kewisch commented on lib/ical/recur_expansion.js
> +          ) - 1;
It appears we're no longer setting ruleDate in this branch. Is that intentional?

2025-06-28 19:17 UTC, kewisch commented on test/recur_expansion_test.js
> +        dates.push(next.toJSDate());
The reason the test is failing is because there is a PERIOD RDATE, which does not have a toJSDate.

2025-06-28 19:17 UTC, kewisch commented
I appreciate that you got this started, but it seems neither you nor me have time to work on this currently. I'm going to close the PR, but if you want to pick this up again any time in the future then you are very much welcome to.

2025-06-28 19:17 UTC, closed without merging