Fix remaining typescript issues
kewisch/ical.js pull request #712
Opened 2024-06-17 11:04 UTC by jannikac

Hi,
according to #707 there are some remaining issues with the generated typescript types. This PR aims to fix everything except those regarding `ICAL.design.designSet` since that is currently broken. Some commits need an explanation:

- Remove `@readonly` tags because it causes this error in typescript: `readonly' modifier can only appear on a property declaration or index signature.`. When the getters get converted to typescript, typescript changes `@readonly` to the typescript keyword `readonly` which is only allowed in index signatures or properties. However you use the `@readonly` tag on getter functions which is not valid in typescript. I couldn't find a way to omit specific valid jsdoc comments from being parsed by typescript (`@ts-ignore` doesnt work and `@ignore` removed the function from the docs).
- Made the options object optional because otherwise it causes `A required parameter cannot follow an optional parameter.`. Also I took a look at the code and believe that `options` itself and their properties should be optional anyways since `options.strictExceptions` is set in the property declaration to false and  `options.exceptions` states that "If not specified exceptions will automatically be set in relation of compoent's parent"

2024-06-18 12:13 UTC, jannikac commented
Managed to fix all the remaining typescript errors, even the `designSet` ones!

PS: I may have to add a test for the breaking change in the register function.

2024-06-18 21:05 UTC, kewisch requested changes

2024-06-18 21:05 UTC, kewisch commented on lib/ical/timezone_service.js
> +  register: function(namedTimezoneOrComponent) {
I'm not a big fan of objects for arguments unless it is very many, as in many cases consumers need to create an object solely for the purpose of passing arguments and then it is destroyed again.

I think we should make it as follows:
* First argument is `Component|Timezone` and required.
* Second argument is String (name) and optional
* If no name is specified, then name is assumed to be timezone.tzid, regardless of if a timezone is passed or a component that is turned into a timezone.
* Runtime error thrown if neither timezone.tzid is set nor name is passed.
* To avoid a breaking change over argument order, a runtime check to see if arg1 is string and arg2 is Timezone, then just swap them correctly. Add a note to the v3 issue to remove the hack when we are ready for v3. Technically it already breaks typescript consumers, but we didn't have types a few weeks ago and the type checks would catch it.

2024-06-19 19:12 UTC, dilyanpalauzov commented
I tried the newest types.

My code so far used `new ICAL.Duration({days: -1})` without a problem.  But the types say this is now invalid, as it misses `isNegative`, `weeks`, `hours`, … elements.  Are `hours`, `weeks` required in the object, passed to the constructor?

I guess the parameter of `event.iterator()` should be optional.

In `Time.fromJSDate()` the second parameter used to be optional - skipping it, was equivalent to passing “false”.  Now this parameter is mandatory. Can it be made optional/default value to be `false`?

While the types enforce that Component.getFirstPropertyValue() returns string, in my existing code I assume that getFirstPropertyValue('dtend' / 'duration' / 'rrule' ) return Time / Duration / Recur object.  Please check, if the return type can indeed be non-string?

Isn’t `getAllSubcomponents(name?: string | undefined): Component[];` redundant - name is either optional, or is (a string or undefined)?

2024-06-21 02:25 UTC, CeeMaxx000 approved these changes

2024-06-21 02:25 UTC, CeeMaxx000 approved these changes

2024-06-21 02:25 UTC, CeeMaxx000 approved these changes

2024-06-21 02:25 UTC, CeeMaxx000 approved these changes

2024-06-26 11:54 UTC, jannikac commented
Hi. I just updated the register function with your suggestion. Should I add a test for the new runtime error aswell?

2024-06-26 18:20 UTC, kewisch approved these changes
Fixing the build warning and these two minor comments and we're good, thank you!

2024-06-26 18:20 UTC, kewisch commented on lib/ical/timezone_service.js
> +      throw new TypeError("neither a timezone nor a name was passed");
```suggestion
      throw new TypeError("Neither a timezone nor a name was passed");
```

2024-06-26 18:20 UTC, kewisch commented on lib/ical/timezone_service.js
> +    if (!timezone.tzid && !name) {
```suggestion
    if (!name) {
```
You already check for the timezone id in the block above and we require the name below.

2024-06-26 18:21 UTC, kewisch commented
> Hi. I just updated the register function with your suggestion. Should I add a test for the new runtime error aswell?

Tests are always well received and maintain coverage, so this would be great!

2024-06-28 10:56 UTC, jannikac commented
Actually I think this test case already covers it, so I didn't add another one:
```js
test('with only invalid component', function() {
      assert.throws(function() {
        let comp = new ICAL.Component('vtoaster');
        subject.register(comp);
      }, "neither a timezone nor a name was passed");
    });
```

Accepted your changes, so now we should be good

2024-06-28 22:31 UTC, merged

2024-06-28 22:31 UTC, kewisch commented
Thank you so much, I've merged the changes and will make a note in the v3 issue.